spring.application.name=global-chat
server.port=${PORT:10000}



spring.datasource.driverClassName=org.h2.Driver
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:postgresql://${dpg-dlb595uuk2g5739cdv3g-a}:${5432}/${chatdb_nj2i}?user=${chatdb_nj2i_user}&password=${2xBi1tC4epuKR0abhk1nj157SL6jVWwu}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.task.scheduling.enabled=true





